### ISSUE TITLE
classNotFoundException: com.github.jcustenborder.kafka.connect.utils.VersionUtil

### ISSUE THREAD

**Issue by cc19941109** [jcustenborder/kafka-connect-mqtt#3]
I did the following:

1. `mvn clean package`

2.  `scp target/kafka-connect-mqtt-0.1-SNAPSHOT.jar <My-Docker-kafka-Volume-Path>`

3.  then `bin/connect-distributed.sh config/connect-distributed.properties`

    but it return :

```[2018-04-02 16:12:31,083] INFO Loading plugin from: /data/k1 (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:184)
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/jcustenborder/kafka/connect/utils/VersionUtil
	at com.github.jcustenborder.kafka.connect.mqtt.MqttSourceConnector.version(MqttSourceConnector.java:41)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.getPluginDesc(DelegatingClassLoader.java:287)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:266)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:206)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:198)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initPluginLoader(DelegatingClassLoader.java:167)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:144)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:47)
	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:70)
Caused by: java.lang.ClassNotFoundException: com.github.jcustenborder.kafka.connect.utils.VersionUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
```

I'm not familiar with Kafka-connect.

How should I modify it

**Comment by cc19941109** [comment]
I know how to do it

I put the files in  ```/usr/local/kafka/plugins``` , and It works very well.

 I submit a stupid question. ..(╯︵╰)
